Lesson_22
Ingodwetrust03/3DGlo- pull request #5
Opened 2021-11-01 18:53 UTC by Ingodwetrust03

2021-11-03 12:43 UTC, DmitryAvilov23 requested changes

2021-11-03 12:43 UTC, DmitryAvilov23 commented on src/modules/smoothScroll.js
> +            var start = performance.now();
Использование var это приступление

2021-11-03 12:43 UTC, DmitryAvilov23 commented on src/modules/smoothScroll.js
> +                  servicesSection.scrollIntoView(top);
Сделать что-то с отступами

2021-11-03 12:43 UTC, DmitryAvilov23 commented on src/modules/tabs.js
> +        if ( e.target.closest('.service-header-tab')){
изменить на

if (!e.target.closest('.service-header-tab') {
  return;
}

это поможет избавиться от вложенности

2021-11-04 21:38 UTC, Ingodwetrust03 commented on src/modules/smoothScroll.js
> +                  servicesSection.scrollIntoView(top);
поправила отступы

2021-11-04 21:38 UTC, Ingodwetrust03 commented on src/modules/smoothScroll.js
> +            var start = performance.now();
убрала этот скрипт

2021-11-06 18:24 UTC, merged